name: Build
on:
  schedule:
    - cron: "0 15 * * 6"
  workflow_dispatch:

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DISCORD_OPTOUTBOT_TOKEN: ${{ secrets.DISCORD_OPTOUTBOT_TOKEN }}
  DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          set -ex

          rm -rf data/

          docker run --rm -v $PWD/data/json:/output tyrrrz/discordchatexporter:2.33.2 exportguild \
            -t ${{ env.DISCORD_TOKEN }} \
            -g ${{ env.DISCORD_SERVER_ID }} \
            -o "/output/%P|%p|%T|%C|%t|%c.json" \
            -f Json \
            --parallel 2

          docker run --rm -v $PWD/data/html:/output tyrrrz/discordchatexporter:2.33.2 exportguild \
            -t ${{ env.DISCORD_TOKEN }} \
            -g ${{ env.DISCORD_SERVER_ID }} \
            -o "/output/%c.html" \
            -f HtmlLight \
            --parallel 2

          docker run --rm -v $PWD/temp/dm:/output tyrrrz/discordchatexporter:2.33.2 exportdm \
            -t ${{ env.DISCORD_OPTOUTBOT_TOKEN }} \
            -o /output \
            -f Json \
            || true

          sudo chown -R $(id -u):$(id -g) data/
          sudo chown -R $(id -u):$(id -g) temp/

          npm ci

          node dev/get_thread_metadata.mjs
          node dev/get_thread_messages.js
          node dev/generate_channel_structure.js

          sudo node --max-old-space-size=8192 dev/opt_out_messages.js
          sudo node --max-old-space-size=8192 dev/add_message_link.js
          sudo node --max-old-space-size=8192 dev/extract_each_message_html.js
          sudo npx js-beautify --file data/html/**/*.html --type html --replace --indent-size 2 --no-preserve-newlines

          node dev/update_search_index.js

          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git add -A
          git commit -m "Update data"
          git push origin HEAD:${GITHUB_REF}
