name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "archiveswiftdevelopersjp"
          entrypoint: "./main.ts" # TODO: update entrypoint
