name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kishikawakatsumi/archive.swiftdevelopers.jp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Koyeb
        run: koyeb service redeploy swift-developers-japan/swift-developers-japan-discussion-archive
